language: node_js
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g npm@^5
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "JWa206tI4rnH0NIg95t1h6n95D2Ww3fc/7XXvT3Mby3iFoPdSnD/AipHmpiYs4MwCY2OFv0DRMeVB3cS8J7W0PJKul0kMNqa2Vt3uWv4Nu+o2SicYmLDORdWPNuOAyt7bEvrjximBtuLflfe+kKt0MKfTOV1xV2hL2Dv3yoLZgX/qQg1woCd/3YK63x0r5WuCJA82f7SsWUXRTsGJQB9FnXihnLIjL+lNHnpJflRqshqepm46WBOVejh6xz0486dsJkhkU2XZp/QY68lcRKMl9sENqGh2ZB6jqXXbrqthmW4EHREw6iqvz4R5qdpqyG7EXYB/0XvsXOD3KCWe/UTxThg3YwQDuw/yYvWZ05H5/HZOEtLt8kE5zCvFLqqa8Y9/U9qL3M3x65DJkUDLONsFkQvi564LDAKHU5bOe6qZ21sw3FHXJx/N632o80nlAALRiUdlzq+Tlmekuk2/RgjEOhj2UhQINUcNR6xXwg8Qh2RkfuQy9osLthYLCEvsiupYyh++9g5hiPg+iKk7JFwJphiq/tUWNUiKX3h5paQQLkp9N9k8rhRhSHMPBV2Q8iiKpUdjUd97T+pVPjjaMkaAZtOObFd1ePmAutmvkLxAoixeH8+dVb7AFDWZm8l5c8CHy/Za/N5OGkSx0TtckfGrg4qK/B3ryso4GIFErhiXwk="
  file:
    - build/_output/labeling.wigt
    - build/_output/labeling-build-info.yml
  on:
    tags: true
    repo: ucfopen/labeling-materia-widget
notifications:
  slack:
    secure: "RwNu+p8GYvMn1Dvq+xEM8llsqH9gU6tVomxAdmLL3AX90Kqati3F5RC5+2LHJON+CYuE/jnHzF/YazNKKFJ2S7vL5QUhIIT/iTKiDK9M/VCyKLCHHQiyC2MwPWQERkA7ftf65aBY8647fliMMR+1NUapSPIpXeum0CAT6K9Z84MDpem/dl5nmCJDGnmuNVdyFgpbF92v9Bgw+sHtZKUZb9p8UcAZ2bKwZtewbZWNVnRDAQbpSfYYPqRqvWQfxcC+ypwiU7JEuHv8Zr8XLGuhdeoX/ky0s9OIudxpxaN4AQPaTnOQpBnAE5Mdn04DIZeU8Lia0mOxJqAQ7eViEQSTN84NHaiEPh+pButcnnrnuzswcBr2uJVXmRO5NGpw26nxLfliwxrv/EgbmSVyUqpv00ZXcBHPDcIo1vzo8kAYMP42AUCP+IbKO+gmgDU9WD2gYDIErNCOFsfUv6X6sZTLqB0nHZUJTE1vj9w+2g5f8odac6gIPsDBy+HrAxlHSkE/+Bxgsii9pUnOTneOrYpyPmHNYtTE1C0iAFjUY6wbGkiuinBOb2laqFOfdiHhRZ6ex3Si4QMDOZdgPV2YPtNOp5jM3CoUVm2BSy3nsvMtWNsJbNXjfdPDn0BLv/+j2LDY/h9+rf0kq6pCTmltS/Otwnyz1ovOi7yfRcOhLzsbj7o="

